# Generated by Django 4.1.3 on 2022-12-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='webiste',
            new_name='website',
        ),
    ]
